export {
  apiRequest,
  apiRequestWithAuth,
  BASE_URL,
  type ApiError,
} from "./client";

export {
  login,
  logout,
  getBalances,
  getProfile,
  healthCheck,
  startBot,
  stopBot,
  resetBot,
  getBotStatus,
  getBotWebSocketURL,
  getStoredToken,
  setStoredToken,
  clearStoredToken,
  type LoginPayload,
  type LoginResponse,
  type BalanceItem,
  type BalancesResponse,
  type ProfileResponse,
  type BotConfigPayload,
  type BotOperationPayload,
  type BotStatusResponse,
} from "./safirion";

export {
  platformLogin,
  platformMe,
  getPlatformBotConfig,
  savePlatformBotConfig,
  getPlatformToken,
  getPlatformUser,
  reconnectBroker,
  setPlatformToken,
  setPlatformUser,
  clearPlatformAuth,
  type PlatformUser,
  type PlatformLoginResponse,
  type PlatformBotConfigResponse,
} from "./platformAuth";
